### ISSUE TITLE
Installation with wheels

### ISSUE THREAD

**Issue by AbdealiLoKo** [AbdealiJK/file-metadata#25]
From https://github.com/AbdealiJK/file-metadata/issues/20

We should give users an easy method to install file-metadata through wheels.
Would creating a wheel for file-metadata mean that none of the dependencies need to be compiled ? If yes, it would be a great value add.

**Comment by AbdealiLoKo** [comment]
Seems like linux wheels are not yet supported - https://www.python.org/dev/peps/pep-0425/
So, this is not very helpful (As we only support linux right now)

**Comment by jayvdb** [comment]
See also https://www.python.org/dev/peps/pep-0513/

**Comment by AbdealiLoKo** [comment]
Currently there is an issue with `python setup.py bdist_wheel` Which needs to be fixed first:

```
Traceback (most recent call last):
  File "setup.py", line 82, in <module>
    'Programming Language :: Python :: Implementation :: CPython'])
  File "/home/ajk/miniconda/envs/py27/lib/python2.7/distutils/core.py", line 151, in setup
    dist.run_commands()
  File "/home/ajk/miniconda/envs/py27/lib/python2.7/distutils/dist.py", line 953, in run_commands
    self.run_command(cmd)
  File "/home/ajk/miniconda/envs/py27/lib/python2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
  File "/home/ajk/miniconda/envs/py27/lib/python2.7/site-packages/wheel/bdist_wheel.py", line 232, in run
    self.distinfo_dir)
  File "/home/ajk/miniconda/envs/py27/lib/python2.7/site-packages/wheel/bdist_wheel.py", line 399, in egg2dist
    distribution=self.distribution)
  File "/home/ajk/miniconda/envs/py27/lib/python2.7/site-packages/wheel/metadata.py", line 176, in pkginfo_to_dict
    new_requirements = sorted(convert_requirements(requirements))
  File "/home/ajk/miniconda/envs/py27/lib/python2.7/site-packages/wheel/metadata.py", line 232, in convert_requirements
    parsed_requirement = pkg_resources.Requirement.parse(req)
  File "/home/ajk/miniconda/envs/py27/lib/python2.7/site-packages/setuptools-21.2.1-py2.7.egg/pkg_resources/__init__.py", line 2833, in parse
ValueError: need more than 0 values to unpack
```

**Comment by AbdealiLoKo** [comment]
Installing with wheels is simple. I've created https://github.com/AbdealiJK/file-metadata/commit/c9bea95e388ee6da9bfa5f99e0ebcbc08b27d635 which fixes the `bdist_wheel` issue and now we can create wheels.
We can make a py27 wheel as file-metadata has no C dependencies. Will do this next time I release

**Comment by jayvdb** [comment]
If you are using environment markers correctly, it can be a 'universal wheel' for all versions. I did this recently for pyexcel (see their git)

**Comment by AbdealiLoKo** [comment]
As we haven't tested the package on py3, nor do we have a travis build for py3, i thought universal wheel can wait till we support py3

**Comment by jayvdb** [comment]
Ah, yes good approach.
