### ISSUE TITLE
Barcode Analysis: Unsupported Image Type

### ISSUE THREAD

**Issue by AbdealiLoKo** [AbdealiJK/file-metadata#32]
From https://travis-ci.org/AbdealiJK/file-metadata/jobs/136607124

```
355 . Analyzing File:UWL Logo Left sub master LCOM 4col.jpg
Exception in thread "main" javax.imageio.IIOException: Unsupported Image Type
    at com.sun.imageio.plugins.jpeg.JPEGImageReader.readInternal(JPEGImageReader.java:1063)
    at com.sun.imageio.plugins.jpeg.JPEGImageReader.read(JPEGImageReader.java:1034)
    at javax.imageio.ImageIO.read(ImageIO.java:1448)
    at javax.imageio.ImageIO.read(ImageIO.java:1400)
    at com.google.zxing.client.j2se.ImageReader.readImage(ImageReader.java:45)
    at com.google.zxing.client.j2se.DecodeWorker.decode(DecodeWorker.java:119)
    at com.google.zxing.client.j2se.DecodeWorker.call(DecodeWorker.java:75)
    at com.google.zxing.client.j2se.CommandLineRunner.main(CommandLineRunner.java:84)
```
- 284 . Analyzing File:TeXML dtd.jpg
- 311 . Analyzing File:UAFS Blue.jpg
- 355 . Analyzing File:UWL Logo Left sub master LCOM 4col.jpg

**Comment by AbdealiLoKo** [comment]
Fixed in https://github.com/AbdealiJK/file-metadata/commit/7fc106548fc4ccc99b5c2d6e82eeaa3fad1e20f8
