### ISSUE TITLE
Barcode Analysis: ArrayIndexOutOfBoundsException

### ISSUE THREAD

**Issue by AbdealiLoKo** [AbdealiJK/file-metadata#34]
From https://travis-ci.org/AbdealiJK/file-metadata/jobs/136607126

```
3 . Analyzing File:Pix.gif
Exception in thread "main" java.lang.ArrayIndexOutOfBoundsException: 1
    at com.google.zxing.common.GlobalHistogramBinarizer.getBlackRow(GlobalHistogramBinarizer.java:71)
    at com.google.zxing.BinaryBitmap.getBlackRow(BinaryBitmap.java:66)
    at com.google.zxing.oned.OneDReader.doDecode(OneDReader.java:132)
    at com.google.zxing.oned.OneDReader.decode(OneDReader.java:54)
    at com.google.zxing.MultiFormatReader.decodeInternal(MultiFormatReader.java:171)
    at com.google.zxing.MultiFormatReader.decode(MultiFormatReader.java:69)
    at com.google.zxing.multi.GenericMultipleBarcodeReader.doDecodeMultiple(GenericMultipleBarcodeReader.java:84)
    at com.google.zxing.multi.GenericMultipleBarcodeReader.decodeMultiple(GenericMultipleBarcodeReader.java:65)
    at com.google.zxing.client.j2se.DecodeWorker.decode(DecodeWorker.java:140)
    at com.google.zxing.client.j2se.DecodeWorker.call(DecodeWorker.java:75)
    at com.google.zxing.client.j2se.CommandLineRunner.main(CommandLineRunner.java:84)
```

**Comment by AbdealiLoKo** [comment]
Fixed in https://github.com/zxing/zxing/issues/607

We should check if the image has more than 3 pixels in width and height as that patch will take some time to get into the .jar files we are downloading
