### ISSUE TITLE
UnicodeEncodeError: 'ascii' codec can't encode character u'\xe7' in position 13: ordinal not in range(128)

### ISSUE THREAD

**Issue by drtrigon** [AbdealiJK/file-metadata#47]
While beta-testing I got this message:

```
$ python file_metadata_bot.py -cat:SVG_files -limit:5
Retrieving 5 pages from commons:commons.
==== [[:File:"Single"Japanese castle Tenshu layout format.svg]] ====
* '''Mimetype:''' image/svg+xml
Time taken to analyze: 1.33984sec

==== [[:File:9th Odia Wikipedia Anniversary.svg]] ====
* '''Mimetype:''' image/svg+xml
Time taken to analyze: 0.968834sec

==== [[:File:A Dine Fork.svg]] ====
* '''Mimetype:''' image/svg+xml
Time taken to analyze: 0.926564sec

==== [[:File:A conceptual drawing of a barge with very simple geometry.svg]] ====
* '''Mimetype:''' image/svg+xml
Time taken to analyze: 1.023462sec

Traceback (most recent call last):
  File "file_metadata_bot.py", line 103, in <module>
    main(*sys.argv)
  File "file_metadata_bot.py", line 97, in main
    log = handle_page(page)
  File "file_metadata_bot.py", line 68, in handle_page
    txt.append('==== {0} ===='.format(page.title(asLink=True, textlink=True)))
UnicodeEncodeError: 'ascii' codec can't encode character u'\xe7' in position 13: ordinal not in range(128)
VERBOSE:pywiki:Dropped throttle(s).
<type 'exceptions.UnicodeEncodeError'>
CRITICAL: Waiting for 1 network thread(s) to finish. Press ctrl-c to abort
CRITICAL:pywiki:Waiting for 1 network thread(s) to finish. Press ctrl-c to abort
VERBOSE:pywiki:All threads finished.
```

**Comment by AbdealiLoKo** [comment]
Hm, looking at the `file_metadata_bot.py` script, seems like I missed the:

```
from __future__ import (division, absolute_import, unicode_literals,
                        print_function)
```

It needs to be add at the top most, below the `# -*- coding: utf-8 -*-`. I've updated the gist appropriately at https://gist.github.com/AbdealiJK/a94fc0d0445c2ad715d9b1b95ec2ba03 too.

I believe that the reason is that `__future__.unicode_literals` was not uploaded which causes side effects with unicode/ascii encoding.

Could you test again and try it out ?

**Comment by drtrigon** [comment]
Sorry for the huge delay, had to setup https://commons.wikimedia.org/wiki/User:DrTrigon/file-metadata together with its gits and do testing. According to the issue you mentioned regarding `analyze_barcode()` I used the patch https://gist.github.com/drtrigon/0002517ea812cc707e6ea2ecaf23d9b3 - no idea whether this is valid, though. Anyway the result is positive, this issue is resolved.
